models:
  - name: dim_listings_cleansed
    description: >
      This table has been cleaned and contains information about listings for Airbnb
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 1000000
          config:
            severity: warn

    columns:
      - name: listing_id
        description: This is a unique identifier for the listing
        data_tests:
          - unique
          - not_null

      - name: host_id
        description: This is a unique identifier for the host
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        description: Type of room
        data_tests:
          - accepted_values:
              arguments:
                values:
                  [
                    "Entire home/apt",
                    "Private room",
                    "Shared room",
                    "Hotel room",
                  ]
      - name: minimum_nights
        description: "{{doc('dim_listing_cleansed__minimum_nights')}}"
        data_tests:
          - positive_values

  - name: dim_listings_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          arguments:
            compare_model: "{{ source('airbnb', 'listings') }}"

  - name: dim_hosts_cleansed
    description: This table has been cleaned and contains information about hosts for Airbnb
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        data_type: integer
      - name: host_name
        data_type: string
      - name: is_superhost
        data_type: string
      - name: updated_at
        data_type: timestamp
      - name: created_at
        data_type: timestamp
